# Generated by Django 5.0.3 on 2024-06-12 16:37

from django.db import migrations, models
from django.utils import timezone

def set_default_timeslots(apps, schema_editor):
    Reservation = apps.get_model('app_cadastro_usuario', 'Reservation')
    Reservation.objects.filter(timeslots=None).update(timeslots=timezone.now())

class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuario', '0004_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeslots',
            field=models.DateTimeField(default=timezone.now)
        ),
        migrations.RunPython(set_default_timeslots)
    ]
