# Generated by Django 5.0.3 on 2024-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuario', '0005_remove_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='timeslots',
            field=models.DateTimeField(),
        ),
    ]
