# Generated by Django 5.0.3 on 2024-06-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuario', '0006_alter_reservation_timeslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='nome',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
