# Generated by Django 5.0.3 on 2024-06-13 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuario', '0008_reservation_data_alter_reservation_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('data', 'timeslots')},
        ),
    ]
