# Generated by Django 5.0.3 on 2024-06-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuario', '0009_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
